/*---------------------------------------------------------------------------*
  Project:  Horizon
  File:     cec_CecSys.h

  Copyright (C)2009-2012 Nintendo Co., Ltd.  All rights reserved.

  These coded instructions, statements, and computer programs contain
  proprietary information of Nintendo of America Inc. and/or Nintendo
  Company Ltd., and are protected by Federal copyright law.  They may
  not be disclosed to third parties or copied or duplicated in any form,
  in whole or in part, without the prior written consent of Nintendo.

  $Rev: 46347 $
 *---------------------------------------------------------------------------*/

//
// Do not edit this file.
// This file is automatically generated.
//

#ifndef NN_CEC_CTR_CEC_CECSYS_H_
#define NN_CEC_CTR_CEC_CECSYS_H_

#include <nn/Handle.h>
#include <nn/Result.h>
#include <nn/types.h>



namespace nn {
namespace cec {
namespace CTR {
namespace detail {

    class CecSys
    {
    public:
        enum Tag
        {
            TAG_IPC_ERROR,
            TAG_OPEN                                             = 0x0001,
            TAG_READ                                             = 0x0002,
            TAG_READ_MESSAGE                                     = 0x0003,
            TAG_READ_MESSAGE_WITH_HMAC                           = 0x0004,
            TAG_WRITE                                            = 0x0005,
            TAG_WRITE_MESSAGE                                    = 0x0006,
            TAG_WRITE_MESSAGE_WITH_HMAC                          = 0x0007,
            TAG_DELETE                                           = 0x0008,
            TAG_SET_DATA                                         = 0x0009,
            TAG_READ_DATA                                        = 0x000a,
            TAG_START                                            = 0x000b,
            TAG_STOP                                             = 0x000c,
            TAG_GET_CEC_INFO_BUFFER                              = 0x000d,
            TAG_GET_CECD_STATE                                   = 0x000e,
            TAG_GET_CEC_INFO_EVENT_HANDLE                        = 0x000f,
            TAG_GET_CHANGE_STATE_EVENT_HANDLE                    = 0x0010,
            TAG_OPEN_AND_WRITE_FILE                              = 0x0011,
            TAG_OPEN_AND_READ_FILE                               = 0x0012,
            TAG_GET_EVENT_LOG                                    = 0x001e,
            TAG_GET_EVENT_LOG_START                              = 0x001f,
            TAG_GET_EVENT_LOG_LENGTH                             = 0x0020,
            TAG_CALC_EVENT_LOG_START                             = 0x0021,
            TAG_SET_CEC_TEST_MODE                                = 0x0401,
            TAG_GET_CEC_INFO_EVENT_HANDLE_SYS                    = 0x0402,
            TAG_IPC_END
        };

    public:
        static Handle s_Session;

    public:
        CecSys() {}

    public:
        static nn::Result Open( u32 cecTitleId, u32 dataType, u32 option, size_t* filesize );
        static nn::Result Read( size_t* pReadLen, u8 pReadBuf[], size_t len );
        static nn::Result ReadMessage( u32 cecTitleId, u8 in_or_out_box, const u8 pMessId[], size_t messIdLen, size_t* pReadLen, u8 pReadBuf[], size_t len );
        static nn::Result ReadMessageWithHmac( u32 cecTitleId, u8 in_or_out_box, const u8 pMessId[], size_t messIdLen, size_t* pReadLen, u8 pReadBuf[], size_t len, const u8 pHmacKey[] );
        static nn::Result Write( const u8 pWriteBuf[], size_t len );
        static nn::Result WriteMessage( u32 cecTitleId, u8 in_or_out_box, u8 pMessId[], size_t messIdLen, const u8 pWriteBuf[], size_t len );
        static nn::Result WriteMessageWithHmac( u32 cecTitleId, u8 in_or_out_box, u8 pMessId[], size_t messIdLen, const u8 pWriteBuf[], size_t len, const u8 pHmacKey[] );
        static nn::Result Delete( u32 cecTitleId, u32 dataType, u8 in_or_out_box, const u8 pMessId[], size_t messIdLen );
        static nn::Result SetData( u32 cecTitleId, const u8 pData[], size_t len, u32 option );
        static nn::Result ReadData( u8 pReadBuf[], size_t len, u32 option, const u8 optionData[], size_t optionDataLen );
        static nn::Result Start( u32 option );
        static nn::Result Stop( u32 option );
        static nn::Result GetCecInfoBuffer( u32 cecTitleId, u8 pCecInfoBuffer[], size_t size );
        static nn::Result GetCecdState( u32* state );
        static nn::Result GetCecInfoEventHandle( nn::Handle* pEventHandle );
        static nn::Result GetChangeStateEventHandle( nn::Handle* pEventHandle );
        static nn::Result OpenAndWriteFile( const u8 pWriteBuf[], size_t writeBufLen, u32 cecTitleId, u32 dataType, u32 option );
        static nn::Result OpenAndReadFile( u8 pReadBuf[], size_t readBufLen, size_t* pReadLen, u32 cecTitleId, u32 dataType, u32 option );
        static nn::Result GetEventLog( u8 pCecExchangeEventsBuf[], s32* pEnd, s32 start, s32 length );
        static nn::Result GetEventLogStart( s32* pStart );
        static nn::Result GetEventLogLength( s32* pLength );
        static nn::Result CalcEventLogStart( s32* pNewStart, s32 start, s32 offset );
        static nn::Result SetCecTestMode( bit8 testMode );
        static nn::Result GetCecInfoEventHandleSys( nn::Handle* pEventHandle );
    };

} // end of namespace detail
} // end of namespace CTR
} // end of namespace cec
} // end of namespace nn



#endif  // ifndef NN_CEC_CTR_CEC_CECSYS_H_
