/*---------------------------------------------------------------------------*
  Project:  Horizon
  File:     os_SvcTypes.autogen.h

  Copyright (C)2009-2012 Nintendo Co., Ltd.  All rights reserved.

  These coded instructions, statements, and computer programs contain
  proprietary information of Nintendo of America Inc. and/or Nintendo
  Company Ltd., and are protected by Federal copyright law.  They may
  not be disclosed to third parties or copied or duplicated in any form,
  in whole or in part, without the prior written consent of Nintendo.

  $Rev: 47347 $
 *---------------------------------------------------------------------------*/

//
// Do not edit this file.
// This file is automatically generated.
//

#ifndef NN_OS_OS_SVCTYPES_AUTOGEN_H_
#define NN_OS_OS_SVCTYPES_AUTOGEN_H_

#include <nn/types.h>
#include <nn/config.h>
#include <nn/os/os_MemoryTypes.h>
#include <nn/dbg/dbg_SmallSet.h>



#ifdef __cplusplus

namespace nn {
namespace os {

typedef void (*ThreadFunc)(uptr param);

struct MemoryInfo
{
    uptr                 baseAddress;
    size_t               size;
    bit32                permission;
    MemoryState          state;
};

struct PageInfo
{
    bit32                flags;
};

struct ThreadContext
{
    bit32                cpuRegisters[13];
    bit32                sp;
    bit32                lr;
    bit32                pc;
    bit32                cpsr;
    bit32                fpuRegisters[32];
    bit32                fpscr;
    bit32                fpexc;
};

struct StartupInfo
{
    s32                  priority;
    size_t               stackSize;
    s32                  argc;
    const char16*        argv;
    const char16*        envp;
};


} // end of namespace os
} // end of namespace nn

#endif  // ifdef __cplusplus




#endif  // ifndef NN_OS_OS_SVCTYPES_AUTOGEN_H_
