/*---------------------------------------------------------------------------*
  Project:  Horizon
  File:     os_Types.h

  Copyright (C)2009-2012 Nintendo Co., Ltd.  All rights reserved.

  These coded instructions, statements, and computer programs contain
  proprietary information of Nintendo of America Inc. and/or Nintendo
  Company Ltd., and are protected by Federal copyright law.  They may
  not be disclosed to third parties or copied or duplicated in any form,
  in whole or in part, without the prior written consent of Nintendo.

  $Rev: 46347 $
 *---------------------------------------------------------------------------*/

/*
    @file

    :include nn/os.h
 */

#ifndef NN_OS_OS_TYPES_H_
#define NN_OS_OS_TYPES_H_

#ifdef  __cplusplus

namespace nn {
namespace os {

enum LimitableResource
{
    LIMITABLE_RESOURCE_MAX_PRIORITY,
    LIMITABLE_RESOURCE_MAX_COMMIT,
    LIMITABLE_RESOURCE_MAX_THREAD,
    LIMITABLE_RESOURCE_MAX_EVENT,
    LIMITABLE_RESOURCE_MAX_MUTEX,
    LIMITABLE_RESOURCE_MAX_SEMAPHORE,
    LIMITABLE_RESOURCE_MAX_TIMER,
    LIMITABLE_RESOURCE_MAX_SHAREDMEMORY,
    LIMITABLE_RESOURCE_MAX_ADDRESSARBITER,
    LIMITABLE_RESOURCE_MAX_CPUTIME,
    LIMITABLE_RESOURCE_END,

    LIMITABLE_RESOURCE_MAX_BIT  = (1u << 31)
};

enum SystemInfoType
{
    SYSTEM_INFO_TYPE_USING_PHYSICAL_MEMORY_SIZE,
    SYSTEM_INFO_TYPE_MAX_USING_PHYSICAL_MEMORY_SIZE,
    SYSTEM_INFO_TYPE_KERNEL_USING_PHYSICAL_MEMORY_SIZE,
    SYSTEM_INFO_TYPE_MAX_KERNEL_USING_PHYSICAL_MEMORY_SIZE,
    SYSTEM_INFO_TYPE_CPU_LOAD,
    SYSTEM_INFO_TYPE_CPU_TIME_INTERRUPTS,
    SYSTEM_INFO_TYPE_CPU_TIME_SYSTEM,
    SYSTEM_INFO_TYPE_CPU_TIME_USER,
    SYSTEM_INFO_TYPE_CPU_TIME_IDLE,
    SYSTEM_INFO_TYPE_NUM_SOFTWARE_INTERRUPTS,
    SYSTEM_INFO_TYPE_NUM_HARDWARE_INTERRUPTS,
    SYSTEM_INFO_TYPE_NUM_INTERRUPTS,
    SYSTEM_INFO_TYPE_NUM_EXCEPTIONS,
    SYSTEM_INFO_TYPE_NUM_RUNNABLE_THREADS,
    SYSTEM_INFO_TYPE_NUM_PAGE_CLEAR,
    SYSTEM_INFO_TYPE_NUM_THREAD_SWITCH,
    SYSTEM_INFO_TYPE_NUM_FPU_SWITCH,
    SYSTEM_INFO_TYPE_NUM_PROCESS_SWITCH,
    SYSTEM_INFO_TYPE_NUM_SYSTEM_CALL,
    SYSTEM_INFO_TYPE_NUM_IPC,
    SYSTEM_INFO_TYPE_NUM_CREATED_THREADS,
    SYSTEM_INFO_TYPE_NUM_CREATED_PROCESSES,
    SYSTEM_INFO_TYPE_NUM_THREADS,
    SYSTEM_INFO_TYPE_NUM_PROCESSES,
    SYSTEM_INFO_TYPE_MAX_NUM_THREADS,
    SYSTEM_INFO_TYPE_MAX_NUM_PROCESSES,
    SYSTEM_INFO_TYPE_NUM_INITIAL_PROCESSES,

    SYSTEM_INFO_TYPE_MAX_BIT = (1u << 31)
};

enum ProcessInfoType
{
    PROCESS_INFO_TYPE_USING_PHYSICAL_MEMORY_SIZE,
    PROCESS_INFO_TYPE_MAX_USING_PHYSICAL_MEMORY_SIZE,
    PROCESS_INFO_TYPE_PRIVATE_PHYSICAL_MEMORY_SIZE,
    PROCESS_INFO_TYPE_MAX_RPIVATE_PHYSICAL_MEMORY_SIZE,
    PROCESS_INFO_TYPE_NUM_HANDLES,
    PROCESS_INFO_TYPE_MAX_NUM_HANDLES,
    PROCESS_INFO_TYPE_NUM_CREATED_THREADS,
    PROCESS_INFO_TYPE_NUM_THREADS,
    PROCESS_INFO_TYPE_MAX_NUM_THREADS,
    PROCESS_INFO_TYPE_CPU_TIME_SYSTEM,
    PROCESS_INFO_TYPE_CPU_TIME_USER,
    PROCESS_INFO_TYPE_CPU_TIME,
    PROCESS_INFO_TYPE_NUM_THREAD_SWITCH,
    PROCESS_INFO_TYPE_NUM_FPU_SWITCH,
    PROCESS_INFO_TYPE_NUM_PROCESS_SWITCH,
    PROCESS_INFO_TYPE_NUM_SYSTEM_CALL,
    PROCESS_INFO_TYPE_NUM_IPC,
    PROCESS_INFO_TYPE_UPTIME,
    PROCESS_INFO_TYPE_NAME,
    PROCESS_INFO_TYPE_REGION,

    PROCESS_INFO_TYPE_MAX_BIT = (1u << 31)
};

enum ThreadInfoType
{
    THREAD_INFO_TYPE_CPU_TIME_SYSTEM,
    THREAD_INFO_TYPE_CPU_TIME_USER,
    THREAD_INFO_TYPE_CPU_TIME,
    THREAD_INFO_TYPE_NUM_THREAD_SWITCH,
    THREAD_INFO_TYPE_NUM_FPU_SWITCH,
    THREAD_INFO_TYPE_NUM_SYSTEM_CALL,
    THREAD_INFO_TYPE_NUM_IPC,
    THREAD_INFO_TYPE_UPTIME,

    THREAD_INFO_TYPE_MAX_BIT = (1u << 31)
};
    
enum HandleInfoType
{
    HANDLE_INFO_TYPE_CREATION_TIME,
    HANDLE_INFO_TYPE_REFERENCE_COUNT,
    HANDLE_INFO_TYPE_PARENT_PROCESS_ID,

    HANDLE_INFO_TYPE_MAX_BIT  = (1u << 31)
};

enum ArbitrationType
{
    ARBITRATION_TYPE_SIGNAL,
    ARBITRATION_TYPE_WAIT_IF_LESS_THAN,
    ARBITRATION_TYPE_DECREMENT_AND_WAIT_IF_LESS_THAN,
    ARBITRATION_TYPE_WAIT_IF_LESS_THAN_WITH_TIMEOUT,
    ARBITRATION_TYPE_DECREMENT_AND_WAIT_IF_LESS_THAN_WITH_TIMEOUT,

    ARBITRATION_TYPE_MAX_BIT = (1u << 31)
};


enum ResetType
{
    RESET_TYPE_ONESHOT,
    RESET_TYPE_STICKY,
    RESET_TYPE_PULSE,

    RESET_TYPE_MAX_BIT = (1u << 31)
};


}	// end of namespace os
}	// end of namespace nn

#endif // __cplusplus

#endif  // ifndef NN_OS_OS_TYPES_H_
