/*---------------------------------------------------------------------------*
  Project:  Horizon
  File:     midi_Midi.h

  Copyright (C)2009-2012 Nintendo Co., Ltd.  All rights reserved.

  These coded instructions, statements, and computer programs contain
  proprietary information of Nintendo of America Inc. and/or Nintendo
  Company Ltd., and are protected by Federal copyright law.  They may
  not be disclosed to third parties or copied or duplicated in any form,
  in whole or in part, without the prior written consent of Nintendo.

  $Rev: 46347 $
 *---------------------------------------------------------------------------*/

//
// Do not edit this file.
// This file is automatically generated.
//

#ifndef NN_MIDI_CTR_MIDI_MIDI_H_
#define NN_MIDI_CTR_MIDI_MIDI_H_

#include <nn/Handle.h>
#include <nn/Result.h>
#include <nn/types.h>
#include <nn/midi/CTR/midi_Api.h>



namespace nn {
namespace midi {
namespace CTR {

    class Midi
    {
    public:
        enum Tag
        {
            TAG_IPC_ERROR,
            TAG_OPEN,
            TAG_CLOSE,
            TAG_GET_DEVICE_INFO,
            TAG_GET_READABLE_LENGTH,
            TAG_READ,
            TAG_IPC_END
        };

    private:
        Handle m_Session;

    public:
        Midi(Handle session) : m_Session(session) {}

    public:
        nn::Result Open();
        nn::Result Close();
        nn::Result GetDeviceInfo( DeviceInfo* pInfo );
        nn::Result GetReadableLength( s32* pSize );
        nn::Result Read( void* pBuf, s32* pReadSize, s32 bufferSize );
    };

} // end of namespace CTR
} // end of namespace midi
} // end of namespace nn



#endif  // ifndef NN_MIDI_CTR_MIDI_MIDI_H_
