/*---------------------------------------------------------------------------*
  Project:  Horizon
  File:     socket_Privileged.h

  Copyright (C)2009-2012 Nintendo Co., Ltd.  All rights reserved.

  These coded instructions, statements, and computer programs contain
  proprietary information of Nintendo of America Inc. and/or Nintendo
  Company Ltd., and are protected by Federal copyright law.  They may
  not be disclosed to third parties or copied or duplicated in any form,
  in whole or in part, without the prior written consent of Nintendo.

  $Rev: 46347 $
 *---------------------------------------------------------------------------*/

//
// Do not edit this file.
// This file is automatically generated.
//

#ifndef NN_SOCKET___SOCKET_PRIVILEGED_H_
#define NN_SOCKET___SOCKET_PRIVILEGED_H_

#include <nn/Handle.h>
#include <nn/Result.h>
#include <nn/types.h>



namespace nn {
namespace socket {

    class Privileged
    {
    public:
        enum Tag
        {
            TAG_IPC_ERROR,
            TAG_STARTUP                                          = 0x0001,
            TAG_CLEANUP                                          = 0x0002,
            TAG_SET_NETWORK_OPT                                  = 0x0003,
            TAG_CLOSE_SOCKETS_OF_PROCESS                         = 0x0004,
            TAG_GET_DEBUG_INFORMATION                            = 0x0005,
            TAG_GET_HOST_ID                                      = 0x0006,
            TAG_GET_ERROR_REPORT_EVENT                           = 0x0007,
            TAG_GET_CONFIG_ERROR                                 = 0x0008,
            TAG_ABORT_STARTUP                                    = 0x0009,
            TAG_IPC_END
        };

    private:
        Handle m_Session;

    public:
        Privileged(Handle session) : m_Session(session) {}

    public:
        nn::Result Startup( const u8 pInstanceConfig[], size_t instanceConfigLength, const u8 pCommonConfig[], size_t commonConfigLength );
        nn::Result Cleanup();
        nn::Result SetNetworkOpt( s32* rval, s32 level, s32 optname, const u8 optval[], s32 optlen );
        nn::Result CloseSocketsOfProcess( bit32 processId );
        nn::Result GetDebugInformation( s32 s, s32 type, u8 info[], size_t len );
        nn::Result GetHostId( u32* hostId );
        nn::Result GetErrorReportEvent( nn::Handle* pEventHandle );
        nn::Result GetConfigError( s32* err );
        nn::Result AbortStartup();
    };

} // end of namespace socket
} // end of namespace nn



#endif  // ifndef NN_SOCKET___SOCKET_PRIVILEGED_H_
