/*---------------------------------------------------------------------------*
  Project:  Horizon
  File:     fnd_PrintResultImpl.cpp

  Copyright (C)2009-2012 Nintendo Co., Ltd.  All rights reserved.

  These coded instructions, statements, and computer programs contain
  proprietary information of Nintendo of America Inc. and/or Nintendo
  Company Ltd., and are protected by Federal copyright law.  They may
  not be disclosed to third parties or copied or duplicated in any form,
  in whole or in part, without the prior written consent of Nintendo.

  $Rev: 46347 $
 *---------------------------------------------------------------------------*/

//
// Do not edit this file.
// This file is automatically generated.
//

#include <nn/Result.h>
#include <nn/fnd/fnd_Result.h>


#define BEGIN_GET_RESULT_DESCRIPTION_STRING_IMPL \
    const char* GetResultDescriptionStringImpl(nn::Result result) \
    { \
        (void)result; \
        if (0) {}

#define CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(nameSpace, description) \
        else if (result.GetDescription() == nameSpace::description) return #description;

#define END_GET_RESULT_DESCRIPTION_STRING_IMPL \
        return 0; \
    }

namespace nn { namespace fnd { namespace detail {



    BEGIN_GET_RESULT_DESCRIPTION_STRING_IMPL
        CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fnd, DESCRIPTION_INVALID_NODE)
        CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fnd, DESCRIPTION_ALREADY_LISTED)
        CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fnd, DESCRIPTION_OUT_OF_RANGE)
        CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fnd, DESCRIPTION_OBSOLETE_RESULT)
    END_GET_RESULT_DESCRIPTION_STRING_IMPL

    void GetResultDescriptionStringImplKeeper()
    {
        const char* (*volatile f)(nn::Result) = GetResultDescriptionStringImpl;
    }

}}}
