/*---------------------------------------------------------------------------*
  Project:  Horizon
  File:     svc_StubDbg.h

  Copyright (C)2009-2012 Nintendo Co., Ltd.  All rights reserved.

  These coded instructions, statements, and computer programs contain
  proprietary information of Nintendo of America Inc. and/or Nintendo
  Company Ltd., and are protected by Federal copyright law.  They may
  not be disclosed to third parties or copied or duplicated in any form,
  in whole or in part, without the prior written consent of Nintendo.

  $Rev: 47347 $
 *---------------------------------------------------------------------------*/

//
// Do not edit this file.
// This file is automatically generated.
//

#ifndef NN_SVC_SVC_STUBDBG_H_
#define NN_SVC_SVC_STUBDBG_H_

#include <nn/types.h>
#include <nn/Handle.h>
#include <nn/Result.h>
#include <nn/os/os_SvcTypes.autogen.h>
#include <nn/os/os_Types.h>
#include <nn/dbg/dbg_SmallSet.h>



#ifdef __cplusplus

namespace nn {
namespace svc {

nn::Result                     Break                         ( nn::dbg::BreakReason reason, const void* data, s32 length );
nn::Result                     OutputDebugString             ( const void* text, s32 length );
nn::Result                     ControlPerformanceCounter     ( bit64* pOut, s32 op, bit32 p0, bit64 p1 );

} // end of namespace svc
} // end of namespace nn

#endif  // ifdef __cplusplus




#endif  // ifndef NN_SVC_SVC_STUBDBG_H_
